# Generated by Django 3.1.4 on 2020-12-13 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('passport_series', models.IntegerField(verbose_name='Серия паспорта')),
                ('passport_number', models.IntegerField(verbose_name='Номер паспорта')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('registration_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес регистрации')),
                ('actual_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фактический адрес')),
                ('questionnaire', models.FileField(blank=True, null=True, upload_to='', verbose_name='Анкета')),
                ('result', models.TextField(blank=True, max_length=2000, verbose_name='Результата проверки')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Обработана', 'Обработана'), ('Ошибка', 'Ошибка'), ('На согласование', 'На согласование'), ('Доп. запрос', 'Доп. запрос'), ('Уточнение данных', 'Уточнение данных'), ('Отклонена', 'Отклонена'), ('Согласована', 'Согласована')], default='Создана', max_length=20, verbose_name='Статус')),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile')),
            ],
        ),
    ]
