# Generated by Django 3.1.5 on 2021-01-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210122_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='surname',
            new_name='last_name',
        ),
    ]
